### ISSUE TITLE
kubectl config (documentation error)

### ISSUE THREAD

**Issue by FlorianLudwig** [antoineco/kOVHernetes#1]
The [tutorial](https://github.com/antoineco/kOVHernetes/blob/master/docs/tutorial.md) states:

> 5. A configuration file for the `kubectl` client tool was written locally

which is more of a wish than a description of what does actually happen as the [source](https://github.com/antoineco/kOVHernetes/blob/master/kovh/main.py#L304) contradicts:

```python
# TODO: generate local kubeconfig file
```

**Comment by antoineco** [comment]
Haha was wondering when someone would spot that one 😅

This wasn't supposed to make it to the doc. I have a working implementation but unfortunately, since you can not know the master's public IP before creating it, you end up having to enable "allow-insecure-tls", which is a bit ugly security-wise.

Maybe I should push it anyway and warn the user.

**Comment by FlorianLudwig** [comment]
I am not fluent in the way this all works yet so I cannot quite follow.

Why can't we write the local kubernetes config after the master was created?

**Comment by antoineco** [comment]
We can, but since communications are done over TLS your API server needs a public DNS name or IP address which matches its certificate, otherwise `kubectl` (rightfully) refuses the connection. It's exactly what happens in your web browser when you [visit a website](https://case.edu/utech/media/caseedu/its-media-library/information-security/chrome-block.png) which has an "insecure" certificate.

Unfortunately OVH Cloud doesn't provide any reverse DNS for its cloud instances, and the public IP of your instances is known only *after* the instance is created. In other words, the Kubernetes API certificate is generated before its public IP is known.

There is an option which allows `kubectl` to accept a certificate regardless of its validity, but if I enable it I have to make it clear in the README, for full security disclosure.

Would that be fine with you?

**Comment by FlorianLudwig** [comment]
That sounds better  than the current state but still not great ;)

Getting a little off-topic here but  I would like to understand the design decisions behind this:

Maybe something like `kubespray` which uses ansible to provision the files to the servers would be more appropriate? What made you make this in the first place instead of building on something existing like kubespray and "just" adding ovh integration on top of that?

**Comment by antoineco** [comment]
Simple: I wanted to toy around with Python and Ignition :)
There is no reason to use this project for a serious deployment, it's just meant to be simple and show good practices.

**Comment by FlorianLudwig** [comment]
Okay, I see.  I was thinking about using it as basis to build something more serious out of it but maybe I will build on something different then :)

Thank you for your time!

PS It might still be a good idea to fix the documentation :]

**Comment by antoineco** [comment]
Indeed if you want a serious setup there are tons of great projects around, I you want a "give me a running Kubernetes in less than 3 minutes" solution this project may be worth a try.

I'll revisit my pending commit ASAP and push the feature instead of fixing the doc.

**Comment by tlvenn** [comment]
Out of curiosity @FlorianLudwig , did you end up using kubespray ? DId you have a look at the open sourced tectonic cli installer as well ?

**Comment by FlorianLudwig** [comment]
@tlvenn I believe this is not the appropriate place to have a sales conversation.

**Comment by tlvenn** [comment]
Sales conversation ?? I think you got something wrong here. While tectonic is indeed a commercial product (I am in no way associated with them), their open source installer allow you to install K8 with Terraform the way they do it in Tectonic. That's it, you dont need a Tectonic license or anything else to use it. And it will install a vanilla K8 cluster as far as I understand.

There is probably some interesting stuff to learn from their Terraform plans.

**Comment by antoineco** [comment]
He's right, this conversation has nothing to do with the original issue.

**Comment by tlvenn** [comment]
Well he is certainly not right sanctioning my post as a sale one, just wanted to clarify at least this point...

I am not trying to sale anything lol. The OP ended up saying he was looking for something more robust to setup his cluster, mentioned Kubespray and therefore I mentioned the tectonic installer thinking he might find it interesting if he did not hear about it (They open sourced it recently).

For reference:
>Tectonic is built on pure-upstream Kubernetes but has an opinion on the best way to install and run a Kubernetes cluster. This project helps you install a Kubernetes cluster the "Tectonic Way". It provides good defaults, enables install automation, and is customizable to meet your infrastructure needs.
> https://github.com/coreos/tectonic-installer

Btw thanks for this project @antoineco !

**Comment by antoineco** [comment]
I'm sure this was just bad wording :)
Tectonic is amazing, feel free to contact each other by email to discuss about it.

**Comment by tlvenn** [comment]
Might find this interesting:
> https://github.com/coreos/tectonic-installer/issues/1932#issue-258570254
